# Generated by Django 2.2.16 on 2022-07-15 12:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220715_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(blank=True, default=uuid.UUID('a811f23c-0436-11ed-ab03-0871908b6167'), max_length=50, verbose_name='Код для авторизации'),
        ),
    ]
