# Generated by Django 2.2.16 on 2022-07-15 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_confirmation_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(blank=True, default='S8QWHN20PD', max_length=50, verbose_name='Код для авторизации'),
        ),
    ]
