# Generated by Django 2.2.16 on 2022-07-15 12:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20220715_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(blank=True, default=uuid.UUID('55b9ac3c-043a-11ed-9e35-0871908b6167'), max_length=50, verbose_name='Код для авторизации'),
        ),
    ]
