# Generated by Django 2.2.16 on 2022-07-15 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_confirmation_code'),
        ('users', '0006_auto_20220715_1533'),
    ]

    operations = [
    ]
