# Generated by Django 2.2.16 on 2022-07-15 15:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_merge_20220715_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(blank=True, default=uuid.UUID('da8d9afa-0456-11ed-9cde-0871908b6167'), max_length=50, verbose_name='Код для авторизации'),
        ),
    ]
