# Generated by Django 2.2.16 on 2022-07-15 16:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20220715_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(blank=True, default=uuid.UUID('f863c9ef-0457-11ed-8968-0871908b6167'), max_length=50, verbose_name='Код для авторизации'),
        ),
    ]
