# Generated by Django 2.2.16 on 2022-07-16 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20220716_1631'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='unique_username_email',
        ),
    ]
