# Generated by Django 2.2.16 on 2022-07-16 18:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20220716_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default=uuid.UUID('3c09944c-0535-11ed-bd91-0871908b6167'), max_length=254, unique=True, verbose_name='Электронная почта'),
        ),
    ]
