# Generated by Django 2.2.16 on 2022-07-14 16:02

from django.db import migrations, models
import titles.validators


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0002_auto_20220714_0408'),
    ]

    operations = [
        migrations.RenameField(
            model_name='titles',
            old_name='categorie',
            new_name='category',
        ),
        migrations.AddField(
            model_name='titles',
            name='description',
            field=models.CharField(default='description', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='genres',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='titles',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='titles',
            name='year',
            field=models.IntegerField(validators=[titles.validators.validate_year]),
        ),
    ]
