# Generated by Django 2.2.16 on 2022-07-19 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0005_auto_20220717_1204'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='genres',
            options={'ordering': ['name']},
        ),
    ]
