# Generated by Django 2.2.16 on 2022-07-20 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0006_auto_20220719_1913'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'ordering': ['name'], 'verbose_name': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='genres',
            options={'ordering': ['name'], 'verbose_name': 'Жанры'},
        ),
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ['name']},
        ),
    ]
